### ISSUE TITLE
RPM Package

### ISSUE THREAD

**Issue by cn137** [scarolan/painless-password-rotation#5]
Hi 
Your script has been of great help and is something that i utilize on a daily basis. I have this built as a pkg internally at my current place of work and i think it will be benficial if this can be made avaialble on Fedora/CentoOS systems as a package.

In short im interested in packaging this for you and making it avaialble as an RPM on Fedora/Centos. I have built several RPM packages internally and want to contribute to the Open Source Community; this will be my first.
Per the packaging guidelines its recommened that we work with a 'Release'. I completely understand if youre adverse to the idea, but it would greatly help in managing and version controlling. Let me know what you think, looking forward to workign with you :)

**Comment by cn137** [comment]
Hi
Just bumping this up.

**Comment by scarolan** [comment]
Hey, sorry for the embarrassingly long delay responding.  I haven't been watching this repo.

If you still want to publish your RPMs let's chat!

**Comment by cn137** [comment]
No worries. Absolutely, let me know what is the best way to reach out and we can discuss in detail.

**Comment by scarolan** [comment]
Sure, let's discuss.  I'm also scarolan at gmail.  Maybe we can host the RPMs as releases on this repo.

**Comment by scarolan** [comment]
closing this out - let's continue discussion via email
